### ISSUE TITLE
node and test snippets don't work

### ISSUE THREAD

**Issue by pdaether** [gaboesquivel/atom-standardjs-snippets#1]
I use Atom 1.0.18 and the node and test snippets don't work for me.
I think Atom doesn't automatically read snippets from subfolders of the `snippets` directory. 
If i move the files to the `snippets`directory, everything is working.

**Comment by capaj** [comment]
I use Atom 1.0.11 and have the same problem.

**Comment by capaj** [comment]
submitted a PR which should fix this: https://github.com/gaboesquivel/atom-standardjs-snippets/pull/2

**Comment by capaj** [comment]
fixed with #2 in 0.1.3 release, confirmed on my ubuntu 8 and Atom 1.0.19, @pdaether maybe you can close this now

**Comment by pdaether** [comment]
Thanks! Works like a charm.

**Comment by gaboesquivel** [comment]
thanks @capaj
