### ISSUE TITLE
a should be bound to await, not Object.assign

### ISSUE THREAD

**Issue by capaj** [gaboesquivel/atom-standardjs-snippets#18]
[V8 implemented async await recently](https://chromium.googlesource.com/v8/v8.git/+/d08c0304c5779223d6c468373af4815ec3ccdb84). In the future, `await` keyword will be utilised very often. Maybe it would be a good idea to have a as `await` instead of `Object.assign`
`Object.assign` could become "oa"

asf would be a good shortcut for `async function(){}`

**Comment by gaboesquivel** [comment]
I agree 👍
