### ISSUE TITLE
Consider dropping atom/language-javascript complementariness

### ISSUE THREAD

**Issue by designorant** [gaboesquivel/atom-standardjs-snippets#20]
Is there a reason this package is complementary to atom/language-javascript while everyone seems to be using [gandm/language-babel](https://github.com/gandm/language-babel) for ES6?

I ask because I've just realised it doesn't come with `switch` snippet, and the one in language-javascript comes with an unnecessary semicolon. There are [other snippets](https://github.com/atom/language-javascript/blob/master/snippets/language-javascript.cson) that don't play well with standard linter too. Wouldn't it be better to drop the complementariness, and simply maintain a Standard fork of Turbo JavaScript?

**Comment by gaboesquivel** [comment]
Yes, thanks @designorant.  For now I simply updated the readme file.  Additional PRs are welcomed :)
