### ISSUE TITLE
CL keybinding creates "class" instead of console.log()

### ISSUE THREAD

**Issue by sdaitzman** [gaboesquivel/atom-standardjs-snippets#22]
Atom 1.13.0

**Comment by gaboesquivel** [comment]
it works fine on my end https://monosnap.com/file/BreAVW0XlFJEfs2aLwNsxSiRQmrD2U

could you please double check.

**Comment by sdaitzman** [comment]
@gaboesquivel I am still experiencing the same issue, and I've been noticing it happening more consistently. Is there any information that I could provide that might be helpful, or a way to check if some other completion provider is conflicting?

**Comment by gaboesquivel** [comment]
@sdaitzman  weird, this is what I see, it lets me choose
 ![](http://pix.toile-libre.org/upload/original/1504895569.png)

perhaps you have a conflicting plugin?  or it is specific OS atom bug ?

**Comment by WillisYe** [comment]
默认情况下 snippet 在 IntelliSense 中的显示优先级并不高，而且在 IntelliSense 中选择相应 snippet 需要按「enter」键，这对于手指短的人来说并不是什么很好的体验。所幸，VSCode 意识到了这一点，并为我们提供了改进的方式。

在 VSCode 的用户设置（「Ctrl+P」在输入框中写「user settings」后点选）中，检索代码段，然后根据提示修改，设置建议优先显示，并且可以通过「TAB」补全 snippet。
"editor.snippetSuggestions": "top",
 "editor.tabCompletion": true,
