### ISSUE TITLE
Keybinding for ctrl-comma 

### ISSUE THREAD

**Issue by gustavoalfaro** [gaboesquivel/atom-standardjs-snippets#26]
The keybinding is blocking the show-settings key binding of the editor

**Comment by gaboesquivel** [comment]
got catch, thanks. will fix.

**Comment by gaboesquivel** [comment]
I think we should drop this commands https://github.com/gaboesquivel/atom-standardjs-snippets#commands  see also https://github.com/gaboesquivel/atom-standardjs-snippets/issues/3 

is anyonse using these ?  I don't use them   @capaj @Kikobeats

**Comment by capaj** [comment]
I"ve migrated to vscode so no 😄

**Comment by gaboesquivel** [comment]
Ha! I looked at it quickly. Feels way more slick than Atom.
