### ISSUE TITLE
Chained methods are annoying

### ISSUE THREAD

**Issue by zaaack** [gaboesquivel/atom-standardjs-snippets#27]
Every time I press dot, all chained methods are showing, can we just remove the dot in prefix?

**Comment by gustavoalfaro** [comment]
You are right there's no intelligent chain, if you dot a object, this shows the methods for every array and object and anything that uses chained methods

**Comment by gaboesquivel** [comment]
@capaj @Kikobeats what do you guys think?   want to remove to dot ?
