### ISSUE TITLE
Reconsider binding ctrl-b

### ISSUE THREAD

**Issue by thedaniel** [gaboesquivel/atom-standardjs-snippets#3]
`ctrl-b` is bound to `core:move-left`, and other users coming from emacs like myself might find it jarring that one, but only one of their core movement commands stopped working. I can of course fix this in my own keybindings file, but I think `ctrl-b` is used commonly enough for movement that you should consider changing the binding or leaving wrap-block's binding empty and up to the user to define.

**Comment by gaboesquivel** [comment]
@thedaniel  Yes, thanks for pointing that out. Do you think `ctrl-{` would be better?
